import { Map } from "@types";

/**
 * Always Axis -> Allies; Top -> Bottom or Left -> Right
 */
export const Strongpoints: Record<
  Map,
  [
    [string, string, string],
    [string, string, string],
    [string, string, string],
    [string, string, string],
    [string, string, string]
  ]
> = {
  Carentan: [
    ["Canal locks", "Rail causeway", "La maison des ormes"],
    ["Customs", "Rail crossing", "Mont halais"],
    ["Canal crossing", "Town center", "Train station"],
    ["Pumping station", "Ruins", "Derailed train"],
    ["Blactot", "502nd start", "Farm ruins"],
  ],
  Foy: [
    ["Road to recogne", "Cobru approach", "Road to noville"],
    ["Cobru factory", "Foy", "Flak battery"],
    ["West bend", "Southern edge", "Dugout barn"],
    ["N30 highway", "Bizory-Foy road", "Eastern ourthe"],
    ["Road to bastogne", "Bois jacques", "Forest outskirts"],
  ],
  Hill: [
    ["Roer river crossing", "Zerkall", "Paper mill"],
    ["Eselsweg junction", "Eastern slope", "Train wreck"],
    ["Flak pits", "Hill 400", "Southern approach"],
    ["Roer river house", "Bergstein church", "Kirchweg"],
    ["Convoy ambush", "Ederhecke junction", "Stuckchen farm"],
  ],
  Hurtgen: [
    ["Grosshau approach", "Hurtgen approach", "Logging camp"],
    ["Hill 15", "Jacob's barn", "Salient 42"],
    ["North pass", "The scar", "The siegfried line"],
    ["Wehebach overlook", "kall trail", "The ruin"],
    ["The mausbach approach", "Reserve station", "Lumber yard"],
  ],
  Kursk: [
    ["Road to kursk", "Ammo dump", "Eastern position"],
    ["Rudno", "Destroyed battery", "The Muddy churn"],
    ["The windmills", "Yamki", "Oleg's house"],
    ["Panzer's end", "Defence in depth", "Listening post"],
    ["Artillery position", "Grushki", "Grushki flak"],
  ],
  PHL: [
    ["Ingouf crossroads", "Road to carentan", "Cabbage patch"],
    ["Madeleine farm", "Madeleine bridge", "Aid station"],
    ["Groult pillbox", "Carentan causeway", "Flak position"],
    ["Jourdan canal", "Douve bridge", "Douve river battery"],
    ["Bloody bend", "Dead man's corner", "Forward battery"],
  ],
  SMDM: [
    ["The corner", "Hill 6", "The fields"],
    ["Hugo's farm", "The hamlet", "St. Marie du Mont"],
    ["The dugout", "AA Network", "Pierre's farm"],
    ["Brecourt battery", "Cattlesheds", "Rue de la gare"],
    ["Winters landing", "Le grand chemin", "The barn"],
  ],
  SME: [
    ["Flak position", "Vaulaville", "La prairie"],
    ["Route du haras", "Western approach", "Rue de Gambosville"],
    ["Hospice", "St. Mere Eglise", "Checkpoint"],
    ["Artillery battery", "The cementry", "Maison du crique"],
    ["Les vieux vergers", "The draw", "Ruisseau de ferme"],
  ],
  Stalingrad: [
    ["Mameyev approach", "Nail factory", "City overlook"],
    ["Dolgiy ravine", "Yellow house", "Komsomol HQ"],
    ["Railway crossing", "Carriage depot", "Train station"],
    ["House of the workers", "Pavlov's house", "The Brewery"],
    ["L-shaped house", "Grudinin's Mill", "Volga banks"],
  ],
  Utah: [
    ["Mammut radar", "Flooded house", "Sainte marie approach"],
    ["Sunken bridge", "La grande crique", "Drowned fields"],
    ["WN4", "The chapel", "WN7"],
    ["AA battery", "Hill 5", "WN5"],
    ["Tare green", "Red roof house", "Uncle red"],
  ],
  Omaha: [
    ["Beaumont road", "Crossroads", "Les isles"],
    ["Rear battery", "Church road", "The orchards"],
    ["West Vierville", "Vierville sur mer", "Artillery battery"],
    ["WN73", "WN71", "WN70"],
    ["Dog green", "The draw", "Dog white"],
  ],
  Remagen: [
    ["Alte liebe barsch", "Bewaldet kreuzung", "Dan radart 512"],
    ["Erpel", "Erpeler ley", "Kasbach outlook"],
    ["St. Severin chapel", "Ludendorf bridge", "Bauernhof am Rhein"],
    ["Remagen", "Möbelfabrik", "Schliefen ausweg"],
    ["Waldburg", "Mühlenweg", "Hägelkreuz"],
  ],
};

/**
 * Always Axis -> Allies; Top -> Bottom or Left -> Right
 */
export const StrongpointImages: Record<
  Map,
  Record<string, { left: number; top: number }>
> = {
  Carentan: {
    "Canal locks": { left: 1464, top: 543 },
    "Rail causeway": { left: 1529, top: 853 },
    "La maison des ormes": { left: 1505, top: 1151 },
    "Customs": { left: 1207, top: 455 },
    "Rail crossing": { left: 1245, top: 729 },
    "Mont halais": { left: 1140, top: 1269 },
    "Canal crossing": { left: 876, top: 388 },
    "Town center": { left: 837, top: 774 },
    "Train station": { left: 810, top: 1046 },
    "Pumping station": { left: 451, top: 496 },
    "Ruins": { left: 554, top: 810 },
    "Derailed train": { left: 438, top: 1062 },
    "Blactot": { left: 180, top: 405 },
    "502nd start": { left: 170, top: 837 },
    "Farm ruins": { left: 146, top: 1141 },
  },
  Foy: {
    "Road to recogne": { left: 334, top: 47 },
    "Cobru approach": { left: 916, top: 45 },
    "Road to noville": { left: 1167, top: 38 },
    "Cobru factory": { left: 494, top: 344 },
    "Foy": { left: 736, top: 435 },
    "Flak battery": { left: 1249, top: 386 },
    "West bend": { left: 315, top: 637 },
    "Southern edge": { left: 810, top: 773 },
    "Dugout barn": { left: 1254, top: 714 },
    "N30 highway": { left: 448, top: 1079 },
    "Bizory-Foy road": { left: 889, top: 1158 },
    "Eastern ourthe": { left: 1246, top: 1059 },
    "Road to bastogne": { left: 287, top: 1382 },
    "Bois jacques": { left: 750, top: 1436 },
    "Forest outskirts": { left: 1258, top: 1434 },
  },
  Hill: {
    "Roer river crossing": { left: 1449, top: 456 },
    "Zerkall": { left: 1540, top: 710 },
    "Paper mill": { left: 1455, top: 1173 },
    "Eselsweg junction": { left: 1075, top: 406 },
    "Eastern slope": { left: 1103, top: 763 },
    "Train wreck": { left: 1117, top: 1205 },
    "Flak pits": { left: 810, top: 454 },
    "Hill 400": { left: 786, top: 789 },
    "Southern approach": { left: 827, top: 1081 },
    "Roer river house": { left: 423, top: 389 },
    "Bergstein church": { left: 518, top: 843 },
    "Kirchweg": { left: 449, top: 1129 },
    "Convoy ambush": { left: 161, top: 449 },
    "Ederhecke junction": { left: 195, top: 810 },
    "Stuckchen farm": { left: 179, top: 1234 },
  },
  Hurtgen: {
    "Grosshau approach": { left: 1508, top: 389 },
    "Hurtgen approach": { left: 1459, top: 810 },
    "Logging camp": { left: 1422, top: 1251 },
    "Hill 15": { left: 1232, top: 452 },
    "Jacob's barn": { left: 1158, top: 859 },
    "Salient 42": { left: 1185, top: 1276 },
    "North pass": { left: 882, top: 308 },
    "The scar": { left: 744, top: 810 },
    "The siegfried line": { left: 781, top: 1165 },
    "Wehebach overlook": { left: 453, top: 436 },
    "kall trail": { left: 463, top: 786 },
    "The ruin": { left: 404, top: 1047 },
    "The mausbach approach": { left: 109, top: 303 },
    "Reserve station": { left: 57, top: 810 },
    "Lumber yard": { left: 64, top: 1116 },
  },
  Kursk: {
    "Road to kursk": { left: 502, top: 1430 },
    "Ammo dump": { left: 771, top: 1403 },
    "Eastern position": { left: 1141, top: 1430 },
    "Rudno": { left: 508, top: 1144 },
    "Destroyed battery": { left: 779, top: 1161 },
    "The Muddy churn": { left: 1222, top: 1137 },
    "The windmills": { left: 537, top: 735 },
    "Yamki": { left: 887, top: 810 },
    "Oleg's house": { left: 1180, top: 842 },
    "Panzer's end": { left: 455, top: 465 },
    "Defence in depth": { left: 810, top: 426 },
    "Listening post": { left: 1182, top: 421 },
    "Artillery position": { left: 492, top: 113 },
    "Grushki": { left: 857, top: 142 },
    "Grushki flak": { left: 1254, top: 154 },
  },
  PHL: {
    "Ingouf crossroads": { left: 447, top: 1447 },
    "Road to carentan": { left: 810, top: 1415 },
    "Cabbage patch": { left: 1241, top: 1462 },
    "Madeleine farm": { left: 462, top: 1075 },
    "Madeleine bridge": { left: 810, top: 1179 },
    "Aid station": { left: 1264, top: 1169 },
    "Groult pillbox": { left: 414, top: 738 },
    "Carentan causeway": { left: 810, top: 810 },
    "Flak position": { left: 1241, top: 780 },
    "Jourdan canal": { left: 373, top: 403 },
    "Douve bridge": { left: 787, top: 546 },
    "Douve river battery": { left: 1125, top: 445 },
    "Bloody bend": { left: 272, top: 103 },
    "Dead man's corner": { left: 810, top: 137 },
    "Forward battery": { left: 1121, top: 125 },
  },
  SMDM: {
    "The corner": { left: 458, top: 1462 },
    "Hill 6": { left: 776, top: 1504 },
    "The fields": { left: 1193, top: 1536 },
    "Hugo's farm": { left: 422, top: 1159 },
    "The hamlet": { left: 810, top: 1208 },
    "St. Marie du Mont": { left: 1261, top: 1247 },
    "The dugout": { left: 440, top: 769 },
    "AA Network": { left: 810, top: 786 },
    "Pierre's farm": { left: 1172, top: 810 },
    "Brecourt battery": { left: 438, top: 381 },
    "Cattlesheds": { left: 810, top: 396 },
    "Rue de la gare": { left: 1172, top: 391 },
    "Winters landing": { left: 415, top: 41 },
    "Le grand chemin": { left: 810, top: 46 },
    "The barn": { left: 1255, top: 63 },
  },
  SME: {
    "Flak position": { left: 135, top: 384 },
    "Vaulaville": { left: 186, top: 762 },
    "La prairie": { left: 157, top: 1144 },
    "Route du haras": { left: 412, top: 427 },
    "Western approach": { left: 439, top: 660 },
    "Rue de Gambosville": { left: 480, top: 1198 },
    "Hospice": { left: 810, top: 339 },
    "St. Mere Eglise": { left: 872, top: 721 },
    "Checkpoint": { left: 782, top: 1138 },
    "Artillery battery": { left: 1193, top: 442 },
    "The cementry": { left: 1084, top: 853 },
    "Maison du crique": { left: 1059, top: 1097 },
    "Les vieux vergers": { left: 1482, top: 503 },
    "The draw": { left: 1513, top: 830 },
    "Ruisseau de ferme": { left: 1515, top: 1181 },
  },
  Stalingrad: {
    "Mameyev approach": { left: 176, top: 311 },
    "Nail factory": { left: 164, top: 868 },
    "City overlook": { left: 147, top: 1255 },
    "Dolgiy ravine": { left: 480, top: 257 },
    "Yellow house": { left: 418, top: 810 },
    "Komsomol HQ": { left: 406, top: 1182 },
    "Railway crossing": { left: 776, top: 369 },
    "Carriage depot": { left: 867, top: 761 },
    "Train station": { left: 781, top: 1104 },
    "House of the workers": { left: 1109, top: 355 },
    "Pavlov's house": { left: 1242, top: 754 },
    "The Brewery": { left: 1193, top: 1195 },
    "L-shaped house": { left: 1452, top: 438 },
    "Grudinin's Mill": { left: 1526, top: 771 },
    "Volga banks": { left: 1499, top: 1205 },
  },
  Utah: {
    "Mammut radar": { left: 155, top: 290 },
    "Flooded house": { left: 155, top: 753 },
    "Sainte marie approach": { left: 185, top: 1297 },
    "Sunken bridge": { left: 516, top: 323 },
    "La grande crique": { left: 526, top: 792 },
    "Drowned fields": { left: 492, top: 1180 },
    "WN4": { left: 865, top: 395 },
    "The chapel": { left: 910, top: 714 },
    "WN7": { left: 790, top: 1276 },
    "AA battery": { left: 1125, top: 357 },
    "Hill 5": { left: 1164, top: 773 },
    "WN5": { left: 1251, top: 1232 },
    "Tare green": { left: 1448, top: 345 },
    "Red roof house": { left: 1464, top: 810 },
    "Uncle red": { left: 1487, top: 1232 },
  },
  Omaha: {
    "Beaumont road": { left: 151, top: 480 },
    "Crossroads": { left: 198, top: 835 },
    "Les isles": { left: 109, top: 1195 },
    "Rear battery": { left: 437, top: 416 },
    "Church road": { left: 474, top: 729 },
    "The orchards": { left: 375, top: 1032 },
    "West Vierville": { left: 836, top: 431 },
    "Vierville sur mer": { left: 960, top: 749 },
    "Artillery battery": { left: 701, top: 1148 },
    "WN73": { left: 1248, top: 384 },
    "WN71": { left: 1255, top: 810 },
    "WN70": { left: 1215, top: 1108 },
    "Dog green": { left: 1541, top: 509 },
    "The draw": { left: 1578, top: 810 },
    "Dog white": { left: 1515, top: 1137 },
  },
  Remagen: {
    "Alte liebe barsch": { left: 415, top: 125 },
    "Bewaldet kreuzung": { left: 792, top: 131 },
    "Dan radart 512": { left: 1215, top: 131 },
    "Erpel": { left: 423, top: 397 },
    "Erpeler ley": { left: 911, top: 392 },
    "Kasbach outlook": { left: 1171, top: 400 },
    "St. Severin chapel": { left: 419, top: 660 },
    "Ludendorf bridge": { left: 828, top: 769 },
    "Bauernhof am Rhein": { left: 1176, top: 915 },
    "Remagen": { left: 458, top: 1154 },
    "Möbelfabrik": { left: 820, top: 1178 },
    "Schliefen ausweg": { left: 1185, top: 1163 },
    "Waldburg": { left: 405, top: 1571 },
    "Mühlenweg": { left: 871, top: 1490 },
    "Hägelkreuz": { left: 1147, top: 1431 },
  },
};

type MapDirection = "ltr" | "rtl" | "ttb" | "btt";

export const MapDirections: Record<Map, MapDirection> = {
  Carentan: "rtl",
  Foy: "ttb",
  Hill: "rtl",
  Hurtgen: "rtl",
  Kursk: "btt",
  PHL: "btt",
  SMDM: "btt",
  SME: "ltr",
  Stalingrad: "ltr",
  Utah: "ltr",
  Omaha: "ltr",
  Remagen: "ttb",
};
